=== yourclassmatee/csc343/csc343db/prep9/books.dtd
<!ELEMENT Books (Book*)>
<!ELEMENT Book (Rating*, Author+, Review*)>
<!ATTLIST Book Title CDATA #REQUIRED>
<!ATTLIST Book Year CDATA #REQUIRED>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Review (Username?)>
<!ATTLIST Review Text CDATA #REQUIRED>
<!ELEMENT Username (#PCDATA)>

=== yourclassmatee/csc343/csc343db/prep9/books.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE Books SYSTEM "books.dtd">

<Books>

<Book Title="AAA" Year="2015">
	<Rating>2</Rating>
	<Rating>5</Rating>
	<Author>AAAA</Author>
	<Review Text="blablabla"/>
</Book>

<Book Title="BBB" Year="2015">
	<Rating>2</Rating>
	<Rating>5</Rating>
	<Author>BBBB</Author>
	<Review Text="blablablabla"/>
</Book>

<Book Title="CCC" Year="2015">
	<Rating>2</Rating>
	<Rating>5</Rating>
	<Author>CCCC</Author>
	<Review Text="blablabla"/>
</Book>



</Books>
